# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-16 18:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0002_auto_20180816_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 46, 8, 348000)),
        ),
        migrations.AlterField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 46, 8, 348000)),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 46, 8, 349000)),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 46, 8, 349000)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 46, 8, 349000)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 46, 8, 349000)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 46, 8, 332000)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 46, 8, 332000)),
        ),
    ]
