# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-16 19:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_reviews', '0003_auto_20180816_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='user123123', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 59, 52, 507000)),
        ),
        migrations.AlterField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 59, 52, 507000)),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 59, 52, 508000)),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 59, 52, 508000)),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 59, 52, 510000)),
        ),
        migrations.AlterField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 59, 52, 510000)),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 59, 52, 469000)),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 16, 13, 59, 52, 469000)),
        ),
    ]
