# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='asdfasdf', max_length=255),
            preserve_default=False,
        ),
    ]
