# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-08 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='career',
            name='students',
        ),
        migrations.AddField(
            model_name='career',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='login_reg.User'),
            preserve_default=False,
        ),
    ]
