# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-14 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_auto_20180812_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_profile',
            field=models.CharField(default='user', max_length=255),
            preserve_default=False,
        ),
    ]
