# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-14 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0004_auto_20180814_0951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
