# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-14 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0007_auto_20180814_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_from',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_to',
        ),
        migrations.AddField(
            model_name='message',
            name='user_from',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to='user_dashboard.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='user_to',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='user_dashboard.User'),
            preserve_default=False,
        ),
    ]
